#!/bin/sh

deployment_root=${DEPLOYMENT_ROOT:-/opt/agentern}
cd "$deployment_root"

if [ -f .deployment.env ]; then
  set -a
  # This file is generated by ops/deploy.sh and contains only image references.
  . ./.deployment.env
  set +a
fi

export COMPOSE_FILE=${COMPOSE_FILE:-compose.yaml:compose.production.yaml:compose.secrets.yaml}
mkdir -p var
