[global]
repo1-type=s3
repo1-retention-full=4
repo1-bundle=y
repo1-block=y
archive-async=y
archive-timeout=5m
process-max=2
start-fast=y
spool-path=/var/spool/pgbackrest
log-level-console=info

[agentern]
pg1-path=/var/lib/postgresql/18/docker
