listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
work_mem = 8MB
wal_level = replica
archive_mode = on
archive_timeout = 900s
archive_command = 'pgbackrest --stanza=agentern archive-push %p'
max_wal_senders = 3
checkpoint_completion_target = 0.9
log_destination = 'stderr'
logging_collector = off
log_min_duration_statement = 1000
password_encryption = scram-sha-256
include_if_exists = '/var/lib/postgresql/18/docker/postgresql.auto.conf'
